<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TC00lab2</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>a7922d33-d106-4e0b-a91b-d1da6cc7442d</testSuiteGuid>
   <testCaseLink>
      <guid>0779cf58-47e4-4c40-9c76-ad4fb3e54e15</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC001-login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92039a87-4093-44f0-8906-3e3d1cfa71c1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8f6d74d0-7b61-42fb-bb51-5c2c8c7d5307</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC002-login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68c2b7ca-0bae-4414-ab22-b5eef7d08085</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3fd678ff-0dcd-4e3a-b52b-ce100ec99973</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC003-login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d9524c1f-7a94-424d-a5c2-3683e656c3e4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ff7175f2-bfbd-44d4-92a9-2a1162a96508</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC004-login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32e79482-f835-452d-b2bc-229d6475f934</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ab722daf-fbf9-4024-bddd-104b4283bee5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC005-login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8dd47cb-ea01-42d6-9cbe-4ac7b66fb7db</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
